name: Deploy Dev to Stage

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure stage branch exists
        run: |
          git fetch --all
          if git show-ref --verify --quiet refs/remotes/origin/stage; then
            echo "Branch stage exists, checking out..."
            git checkout stage
          else
            echo "Branch stage does not exist, creating it..."
            git checkout -b stage
            git push origin stage
          fi

      - name: Deploy dev to stage
        run: |
          RELEASE_DATE=$(date '+%Y-%m-%d')
          git merge origin/dev --no-ff -m "Release dev -> stage ${RELEASE_DATE}"
          git push origin stage